# Generated by Django 3.2.25 on 2026-07-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.PositiveSmallIntegerField()),
                ('q2', models.PositiveSmallIntegerField()),
                ('q3', models.PositiveSmallIntegerField()),
                ('q4', models.PositiveSmallIntegerField()),
                ('q5', models.PositiveSmallIntegerField()),
                ('q6', models.PositiveSmallIntegerField()),
                ('q7', models.PositiveSmallIntegerField()),
                ('q8', models.PositiveSmallIntegerField()),
                ('q9', models.PositiveSmallIntegerField()),
                ('q10', models.PositiveSmallIntegerField()),
                ('q11', models.PositiveSmallIntegerField()),
                ('q12', models.PositiveSmallIntegerField()),
                ('q13', models.PositiveSmallIntegerField()),
                ('q14', models.PositiveSmallIntegerField()),
                ('q15', models.PositiveSmallIntegerField()),
                ('q16', models.PositiveSmallIntegerField()),
                ('q17', models.PositiveSmallIntegerField()),
                ('q18', models.PositiveSmallIntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_FormularioFunQ.aluno')),
            ],
        ),
    ]
