# Generated by Django 3.2.25 on 2026-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FormularioFunQ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaformulario',
            name='q19_opiniao_atividade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respostaformulario',
            name='q20_sentimento_jogo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respostaformulario',
            name='q21_compreensao_conceitos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respostaformulario',
            name='q22_fator_interesse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respostaformulario',
            name='q23_pontos_negativos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respostaformulario',
            name='q24_sugestoes_mudanca',
            field=models.TextField(blank=True, null=True),
        ),
    ]
