# Generated by Django 3.2.25 on 2026-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FormularioFunQ', '0002_auto_20260817_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaformulario',
            name='grupo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo de Teste'),
        ),
        migrations.AddField(
            model_name='respostaformulario',
            name='pesquisador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pesquisador'),
        ),
    ]
