# Generated by Django 3.2.25 on 2026-10-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_FormularioFunQ', '0003_auto_20260909_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
    ]
